// <auto-generated />
namespace WebBanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Table_Wishlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_Wishlist));
        
        string IMigrationMetadata.Id
        {
            get { return "202403261920039_Table_Wishlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
